export const BANK_LIST_REQUEST = "BANK_LIST_REQUEST";
export const BANK_LIST_SUCCESS = "BANK_LIST_SUCCESS";
export const BANK_LIST_FAILURE = "BANK_LIST_FAILURE";
export const FILTERED_BANK_LIST = "SET_FILTERED_BANK_LIST";
